### ISSUE TITLE
Installations fails, missing  requirement pybonjour

### ISSUE THREAD

**Issue by torarnv** [square/PonyDebugger#100]
```
{vegas:~} $ curl -sk https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py | python - --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger
New python executable in /Users/user/Library/PonyDebugger/bin/python
Installing setuptools................done.
Installing pip..............done.
Obtaining ponydebugger from git+https://github.com/square/PonyDebugger.git#egg=ponydebugger
  Updating ./Library/PonyDebugger/src/ponydebugger clone
  Running setup.py (path:/Users/user/Library/PonyDebugger/src/ponydebugger/setup.py) egg_info for package ponydebugger

  Installing extra requirements: 'egg'
Downloading/unpacking tornado (from ponydebugger)
  Downloading tornado-3.1.1.tar.gz (374kB): 374kB downloaded
  Running setup.py (path:/Users/user/Library/PonyDebugger/build/tornado/setup.py) egg_info for package tornado

    warning: no previously-included files matching '_auto2to3*' found anywhere in distribution
Downloading/unpacking pybonjour (from ponydebugger)
  Could not find any downloads that satisfy the requirement pybonjour (from ponydebugger)
  Some externally hosted files were ignored (use --allow-external pybonjour to allow).
Cleaning up...
No distributions at all found for pybonjour (from ponydebugger)
Storing debug log for failure in /Users/user/.pip/pip.log
Traceback (most recent call last):
  File "<stdin>", line 2462, in <module>
  File "<stdin>", line 946, in main
  File "<stdin>", line 1794, in after_install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/user/Library/PonyDebugger/bin/pip', 'install', '-U', '-e', 'git+https://github.com/square/PonyDebugger.git#egg=ponydebugger']' returned non-zero exit status 1
```

**Comment by kxalex** [comment]
1. Download bootstrap-ponyd.py
2. Change line 1794 in bootstrap-ponyd.com to
                     'install', '-U', '-e', 'git+https://github.com/square/PonyDebugger.git#egg=ponydebugger', '--allow-external', 'pybonjour', '--allow-unverified', 'pybonjour'])
3. Re-run scripts
    cat bootstrap-ponyd.py | \
  python - --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger

**Comment by bulwinkel** [comment]
thanks @kxalex, worked a treat!

**Comment by mooshee** [comment]
@kxalex +1, worked for me as well

**Comment by dodyrw** [comment]
@Bruno-Furtado thanks you, I installed with the same way with you
`sudo pip install -U -e git+https://github.com/square/PonyDebugger.git#egg=ponydebugger --allow-external pybonjour --allow-unverified pybonjour`

Before that I install pip `sudo easy_install pip`

**Comment by Derimagia** [comment]
This is still an issue - The recommended fix from @kxalex did not work for me, but I believe it's because pip was updated. I"m getting the following deprecation warnings errors

DEPRECATION: --allow-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
DEPRECATION: --allow-unverified has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.

Mac
Pip 8.0.2
Homebrew Python 2.7.10_2

**Comment by isaacselement** [comment]
@derimagia  Agree , This is still an issue !

**Comment by koblee** [comment]
pip install -U -e git+https://github.com/square/PonyDebugger.git#egg=ponydebugger --allow-external pybonjour --allow-unverified pybonjour
DEPRECATION: --allow-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
DEPRECATION: --allow-unverified has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
Obtaining ponydebugger from git+https://github.com/square/PonyDebugger.git#egg=ponydebugger
  Updating ./Library/PonyDebugger/src/ponydebugger clone
  Running setup.py (path:/Users/alex/Library/PonyDebugger/src/ponydebugger/setup.py) egg_info for package ponydebugger produced metadata for project name ponyd. Fix your #egg=ponydebugger fragments.
Collecting tornado (from ponyd)
  Using cached tornado-4.3.tar.gz
Collecting pybonjour (from ponyd)
  Could not find a version that satisfies the requirement pybonjour (from ponyd) (from versions: )
No matching distribution found for pybonjour (from ponyd)

**Comment by derimagia** [comment]
Relevant Pull Request: https://github.com/square/PonyDebugger/pull/184

**Comment by koblee** [comment]
thanks, it looks like its well known - from [174](https://github.com/square/PonyDebugger/issues/174) this made it to install from different repo?
`pip install -e git+https://github.com/Eichhoernchen/pybonjour.git#egg=pybonjour`
