### ISSUE TITLE
Simulator cannot get data from network, seems like pony didn't send back the data

### ISSUE THREAD

**Issue by vincentsong** [square/PonyDebugger#103]
My project is using ReactiveCocoa to wrap AFNetworking operations. I just tried with PonyDebugger, and I can see the network request and response from Chrome. But the simulator cannot get the data, is this as design? Is there any sniffer function?

**Comment by asmallteapot** [comment]
Error code `-999` is [NSURLErrorCancelled](https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes/nsurlerrorcancelled?language=objc), which could have occurred either in your app, the web service you were trying to connect to, or somewhere in PonyDebugger.

This issue is a few years old, so I'm going to go ahead and close it for now. If you're still having this problem, please feel free to re-open with more information about the request that's failing and what you're seeing in PonyDebugger.
